### ISSUE TITLE
Implement full working main menu

### ISSUE THREAD

**Issue by eliasdjup** [inf112-v20/G-Unit#11]
Implement a menu where the user is able to choose play or quit. Also options for joining or hosting a game.

**Comment by boaanes** [comment]
# Additional features
-   Add buttons for:
    -   Host a game (new screen where IP pops up for sharing to other players)
        -   Buttons for selecting how many players, and for starting the game
    -   Join a game (user gets prompted for IP input)
        -   Game pops up when host starts the game
    -   Quit-knapp
